### ISSUE TITLE
사용자 로그인 방식 구현 방식

### ISSUE THREAD

**Issue by Planybirth** [SUVID-18/tag_management#10]
- 기기변경을 통한 대리출결을 막기 위해 전통적인 로그인 방식만을 구현하는 것은 보안 상 허점이 많다고 생각됨.
- 따라서 OAuth 2.0을 포함한 로그인과 생체인증을 통한 추가인증을 같이 포함하는 것이 좋을 것 같음.

**Comment by sun30812** [comment]
그러면 추후 로그인 시 생체인식을 활용하는 방법을 도입하면 될 것으로 보이네

[local_auth](https://pub.dev/packages/local_auth) 플러그인이 생체인증을 하게 해주는 플러그인이니 고려하면 될 듯

**Comment by Planybirth** [comment]
오케이!
