### ISSUE TITLE
NFC 태그 앱에서 사용하는 테이블

### ISSUE THREAD

**Issue by sun30812** [SUVID-18/tag_management#11]
# NFC 태그 앱에서 사용하는 테이블

NFC태그를 유지보수하는 앱에서는 아래와 같은 테이블을 가져도 괜찮지 않나 생각함

| UUID | 강의실 위치 |
|--------|--------|
| ???????? | IT 000호 |
| ???????? | IT 001호 |

위 같이 두가지 속성만 존재하면 될 것 같다고 보임.

과목 별 인증시간은 NFC 태그 관리 앱이 아닌 교수용 전자출결 앱에서 해당 테이블의 UUID만 끌어와서 시간을 기재하는 방식으로 해도 되지 않을 까 싶다..

_Originally posted by @sun30812 in https://github.com/SUVID-18/tag_management/issues/4#issuecomment-1493778722_

**Comment by Planybirth** [comment]
태그된 사람 정보 -> 학생 테이블에서 가져올 수 있음
태그한 시간 -> 교수가 쓰는 테이블의 체크인 가능시간과 현재시간과 비교해도 됨

더 필요한 정보는 그럼 없는거겠지?

**Comment by sun30812** [comment]
그런듯.
NFC 관리 앱의 DB 테이블은 완성인 것 같음
