### ISSUE TITLE
서버에 등록된 태그 및 강의실 정보 관리 기능

### ISSUE THREAD

**Issue by sun30812** [SUVID-18/tag_management#3]
# 서버에 등록된 태그 및 강의실 정보 관리 기능

서버에 등록된 태그 정보나 강의실 정보를 확인하고 수정하는 기능입니다.  

- 태그 등록 당시 입력했던 강의실 위치(**강의를 진행하는 과목의 이름을 바꾸는 경우가 아님**) 반환하기
- 강의실 위치 수정 시 수정 내역을 업로드 할 수 있어야 함
- DB 읽기/쓰기는 로그인 후 사용 가능하도록 해야 함

**Comment by sun30812** [comment]
@dongminii 이건 화면 구성이 아니라 백엔드 작업을 하는 것이기에 너가 할당받는게 아님

**Comment by Planybirth** [comment]
강의실 위치 수정 내역 반영은 일단 보류.
