### ISSUE TITLE
NFC 태그 앱 Firebase 정책 설정

### ISSUE THREAD

**Issue by sun30812** [SUVID-18/tag_management#4]
# NFC 태그 앱 Firebase 관련 정책 설정
NFC태그 관리 앱 사용 대상자의 인증 방식에 관한 정책을 구성합니다.

**Comment by sun30812** [comment]
아래 요소들을 정하면 될 듯
- Firebase 프로젝트는 누가 생성할까
- 사용자 인증 방식을 어떻게 할까?
- 데이터 베이스는 어떻게 정의할까
- 누구에게 어떤 요소(데이터)까지 접근(읽기/쓰기)을 가능하게 할까
@Planybirth

**Comment by Planybirth** [comment]
1. 테이블 정의 및 ERD 완성 이후 결정해야 할 것 같음.

2. 사용자 인증 방식은 새로운 이슈를 파서 별도로 기재하였음.

**Comment by Planybirth** [comment]
3. 존재해야 하는 테이블 목록
- 학생 출석 여부 테이블
- 학생 정보 테이블 ( 학교 데이터베이스 서버로부터 받은 정보 )
- 전체 과목 테이블
- 전체 교수 테이블

**Comment by Planybirth** [comment]
4. 사용자별 접근 가능한 테이블 목록
학생이 조회 가능한 테이블
- 학생 출석 여부 테이블 ( 본인 한정 )
- 학생 정보 테이블 ( 본인 한정 )
	- 시간표 조회
- 과목 테이블 ( 본인 과목 한정 )

추후 기기변경 시 휴대폰 인증 같은 절차를 거치면, 학생 정보 테이블의 고유 키가 수정될 수는 있지만, 직접적으로 학생이 테이블을 수정하는 일은 없을 것 같음.

교수가 수정 가능한 테이블
- 학생 출석 여부 테이블
- 과목 테이블 ( 다른 테이블로 변경될 수 있음 )
	- 인증시간 설정
	- 과목 출석 여부 결정 ( 휴강 또는 다른 사유로 변경될 수 있으므로 )

교수가 조회 가능한 테이블
- 교수 테이블 ( 본인 한정 )
- 학생 출석 여부 테이블 ( 본인 과목 한정 )
- 과목 테이블 ( 본인 한정 )

**Comment by Planybirth** [comment]
- NFC 관련 테이블은 어떻게 처리해야 할 지 모르겠음.
	- 과목의 인증시간을 설정하는 테이블을 별도로 만들 것인지?
@sun30812

**Comment by sun30812** [comment]
NFC 태그 앱에서 사용하는 테이블은 사실상 아주 단순하지 않나 생각함.

| UUID | 강의실 위치 |
|--------|--------|
| ???????? | IT 000호 |
| ???????? | IT 001호 |

같이 두가지 속성만 존재하면 될 것 같다고 보임.

과목 별 인증시간은 NFC 태그 관리 앱이 아닌 교수용 전자출결 앱에서 해당 테이블의 UUID만 끌어와서 시간을 기재하는 방식으로 해도 되지 않을 까 싶다..

**Comment by sun30812** [comment]
프로젝트 생성자만 정하면 사실상 마무리가 될 것 같음. 아래 요소들을 사용할 것으로 보이니 확인 바람

- Firestore: No SQL기반의 클라우드 DB
- Authentication: 사용자 인증
- Dynamic Link: 태그만으로 앱 내 특정 페이지(출결 페이지)로 이동

비용상 문제를 없을 것으로 판단함(=무료)

**Comment by Planybirth** [comment]
@sun30812 프로젝트 생성자는 네가 해주셈
글고 구성원으로 넣어주라

**Comment by sun30812** [comment]
> @sun30812 프로젝트 생성자는 네가 해주셈
> 글고 구성원으로 넣어주라

방금 추가했어. 잘 되나 확인해봐

**Comment by sun30812** [comment]
그럼 해당 이슈를 닫겠습니다.
